# Generated by Django 3.1.7 on 2021-04-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAuthor', models.CharField(max_length=150)),
                ('lastNameAuthor', models.CharField(max_length=150)),
                ('nationalityAuthor', models.CharField(max_length=100)),
                ('descriptionAuthor', models.TextField()),
                ('createDateAuthor', models.DateTimeField(auto_now_add=True)),
                ('updateDateAuthor', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['nameAuthor'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleBook', models.CharField(max_length=150)),
                ('publicationDateBook', models.DateField()),
                ('createDateBook', models.DateTimeField(auto_now_add=True)),
                ('updateDateBook', models.DateTimeField(auto_now=True)),
                ('authorId', models.ManyToManyField(to='book.Author')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['titleBook'],
            },
        ),
    ]
