# Generated by Django 3.1.7 on 2021-04-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='imageAuthor',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='book/authors/'),
        ),
        migrations.AddField(
            model_name='book',
            name='amountBook',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='descriptionBook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='imageBook',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='book/books/'),
        ),
    ]
