# Generated by Django 3.1.7 on 2021-04-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
