# Generated by Django 3.1.7 on 2021-04-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='expirationDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
